### ISSUE TITLE
macOS version?

### ISSUE THREAD

**Issue by Tatuy** [OTCv8/otclientv8#10]
I see you compiled and released the version for Linux, very good work, genius. Hey could you get the macOS version?

**Comment by bbarwik** [comment]
I don't have mac. Currently it's not planned. You can use wine for that.

**Comment by username-3** [comment]
> I don't have mac. Currently it's not planned. You can use wine for that.

Wine is not supported on the latest version of macOS 10.15 because of dropped 32-bit support.
