### ISSUE TITLE
Has offset and set target

### ISSUE THREAD

**Issue by Sajgon** [OTCv8/otclientv8#102]
Hi, I have a case I consider a bug, I am not sure if its only my v8 version or master aswell.

When an outfit has offset in object builder, for example 8 that is common
![image](https://user-images.githubusercontent.com/6536543/103171320-b0269e00-484b-11eb-9983-d0e52dc7a9d3.png)

then the attack area has offset aswell, when it should not. it makes it really hard to auto attack monster or players on screen when they are running.
![image](https://user-images.githubusercontent.com/6536543/103171307-8ec5b200-484b-11eb-84d9-4abe8573be44.png)
As you can see here the red targeting area should be equal to the blue hovered area.

**Comment by OTCv8** [comment]
Corrected in 2.6.1

**Comment by Sajgon** [comment]
Hello @OTCv8 , looks like unfortunately it's not fixed in 2.6.1.
![image](https://user-images.githubusercontent.com/6536543/104911286-e9ee4e80-598a-11eb-9b7a-1fde45cd89ec.png)
