### ISSUE TITLE
Magic level limit 255

### ISSUE THREAD

**Issue by BoTeQX** [OTCv8/otclientv8#103]
Hey, I found that there is a max value for magic level (255).
Please can you change it :)

**Comment by OTCv8** [comment]
Activate feature GameDoubleMagicLevel

**Comment by BoTeQX** [comment]
I use clean otclient 2.6.1 + clean otclient tfs with enabled GameDoubleMagicLevel
`ERROR: ProtocolGame parse message exception (9511 bytes, 3031 unread, last opcode is 0x1c (28), prev opcode is 0x00 (0)): unhandled opcode 28
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1098)`
[packet.log](https://github.com/OTCv8/otclientv8/files/5827133/packet.log)
