### ISSUE TITLE
Aim on battle list is unreliable #gamebreaking

### ISSUE THREAD

**Issue by thatmichaelguy** [OTCv8/otclientv8#105]
_updated 28/01/21 with more information_

When aiming on battle list, if the creature is moving, the client often targets the floor tile where the creature was instead of the creature itself, which causes the server to return `RETURNVALUE_CANONLYUSETHISRUNEONCREATURES` if the rune requires a creature target.
I've tried offsetting to account for this but ultimately been unsuccessful (I think) due to variable creature speeds.

The code below executes when you manually aim a rune on the battle list.
```lua
    local creature = clickedWidget:getCreature()
    if creature then
      g_game.useWith(selectedThing, creature, selectedSubtype)
    end
```
`clickedWidget:getCreature()` passes the position that the creature is in at the moment of clicking to `g_game.useWith` which uses that position.

I've tried changing this to work with the creatureId instead but get the same result:
```lua
    local creature = clickedWidget:getCreature()
    local creatureId = creature:getId()
    if creature then
      g_game.useWith(selectedThing, g_map.getCreatureById(creatureId), subType)
    end
```

The issue may also be heavily latency based. If the client is collecting and passing the creature pos according to the client (which may be 100+ ms behind server), there is more chance that when the server registers the action, the creature will no longer be at the position.

**Comment by Oen44** [comment]
More people are reporting this issue, @OTCv8 fix is needed.

**Comment by Zetiyapay** [comment]
i have same issue... :/
