### ISSUE TITLE
setImageSmooth doesn't working

### ISSUE THREAD

**Issue by JosensGames** [OTCv8/otclientv8#106]
Hello, I've spent a lot of time looking in the files to see if I can disable anti aliasing, and, after hours I have found this on luafunctions.cpp

`g_lua.bindClassMemberFunction<UIWidget>("setImageSmooth", &UIWidget::setImageSmooth);`

When I try to use the command
`UIWidget.setImageSmooth(false)`

The console drops the next error
`ERROR: command failed: C++ call failed: LUA ERROR: attempt to cast a 'boolean' lua value to 'class stdext::shared_object_ptr<class UIWidget>'
stack traceback:
    [builtin#146]: at 0x009b2490
    [C]: in function 'setImageSmooth'
    :1: in main chunk
    [C]: in function 'pcall'
    /modules/client_terminal/terminal.lua:376: in function 'executeCommand'
    /modules/client_terminal/terminal.lua:104: in function </modules/client_terminal/terminal.lua:102>
    [C]: in function 'pcall'
    /modules/corelib/util.lua:311: in function </modules/corelib/util.lua:309>
stack traceback:
    [builtin#146]: at 0x009b2490
    [C]: in function 'setImageSmooth'
    :1: in main chunk
    [C]: in function 'pcall'
    /modules/client_terminal/terminal.lua:376: in function 'executeCommand'
    /modules/client_terminal/terminal.lua:104: in function </modules/client_terminal/terminal.lua:102>
    [C]: in function 'pcall'
    /modules/corelib/util.lua:311: in function </modules/corelib/util.lua:309>`

Here appears that Lua is sending a boolean as parameter, but the application just accept a class called "class stdext::shared_object_ptr<class UIWidget>" as parameter.

The question is, How do I fix that?
I'm scripting a shader to create my own AntiAliasing system. Thanks.

**Comment by OTCv8** [comment]
It should be UIWidget:setImageSmooth(false)
