### ISSUE TITLE
12.52 Version with TFS 1.3 12.60 ( 12.52-12.60 )

### ISSUE THREAD

**Issue by kungen32** [OTCv8/otclientv8#119]
Hello,

We want to know, coupling OTCv8 to OtservBR 12.60 version, what we need to change in Sources for make compatible the Otcv8 with the server?

Im using TFS 1.3 OtservBR 12.60, when try login give's an error ' Only protocols 12.60 Allowed ', anyone has posted in sources need make changes, but there is no information how to do it, i post on Otservbr community, but they send me to ask here about this.

I just want to use 12.52 - 12.60 Version ( 12.52 Otcv8 , and 12.60 normal tibia client ) , i see it's possible but cannot find any tutorial about this.

Thanks in advance

**Comment by daniofordon** [comment]
do you know when the update will come out?

**Comment by OTCv8** [comment]
Hey, there's no tibia 12+ support yet

**Comment by kungen32** [comment]
Ok, there is no Support, i can play with 12.52 Version On Server, and with OtservBR downgraded into a 12.50 Version.
But i am using a 12.60 Server and i want to accept Older version of tibia client, this is possible using allowclientold=yes and doing changes in sources, cause you can play with a client 10 Also.
I think maybe you dont know, but anyone surely know how downgrade a 12.60 ( cause is not allowed by protocologame ) to play with another client, it gives and error Mysql, after reading it, i will understand they dont know where look into Account, cause in teory is email, but also otserv has bloqued Otcv8 Cause you can make crash server doing some things.
Just shit they disable it.. they update the game but you cannot got a previous version.

Well thanks you Otcv8 for your reply , i know is possible we have tested another kind of 12.60 , i was just wondering to know what hapens this 12.60 doesnt work ( otservbr ) with otcv8 , and 12.60 baiak for example i can enter with otcv8 12.52 and allow previous version, cause is in sources, i have asked on otservbr forum, and they send me to post the issue here XD
Well, thanks again :)
