### ISSUE TITLE
Error in libzip.so.4

### ISSUE THREAD

**Issue by Rechdan** [OTCv8/otclientv8#121]
Here is the error I'm getting when trying to run in Ubuntu:
`./otclient_linux: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory`

**Comment by Beats-Dh** [comment]
I am also trying this same problem, I tried to solve it yesterday but without success. I'm using Ubuntu 20.10

**Comment by Rechdan** [comment]
> I am also trying this same problem, I tried to solve it yesterday but without success. I'm using Ubuntu 20.10

My Ubuntu is 20.04, but yeah, the problem seems the same for both versions

**Comment by Beats-Dh** [comment]
Possible solution: https://github.com/xournalpp/xournalpp/issues/2610

**Comment by Beats-Dh** [comment]
I'm getting this error right now:
`== application started at Mar 24 2021 11:44:43
OTCv8 2.6 rev 0 (devel) made by otclient.ovh built on Nov 16 2020 for arch x64
Loaded module 'corelib'
Loaded module 'crash_reporter'
Loaded module 'gamelib'
Loaded module 'client'
Loaded module 'client_styles'
Locale 'pl' is missing 1 translations.
["Total Price:"] = "",
Locale 'pt' is missing 19 translations.
["Account Status:"] = "",
["Action:"] = "",
["Amount:"] = "",
["Balance:"] = "",
["Comment:"] = "",
["Don't stretch/shrink Game Window"] = "",
["Find:"] = "",
["Name:"] = "",
["Offer Type:"] = "",
["Piece Price:"] = "",
["Position:"] = "",
["Price:"] = "",
["Reason:"] = "",
["Search:"] = "",
["Statement:"] = "",
["Total Price:"] = "",
["Weight:"] = "",
["Your Capacity:"] = "",
["Your Money:"] = "",
Loaded module 'client_locales'
Loaded module 'client_topmenu'
Loaded module 'client_background'
Loaded module 'client_textedit'
Loaded module 'client_options'
Loaded module 'client_entergame'
Loaded module 'game_things'
Loaded module 'game_features'
Loaded module 'client_terminal'
Loaded module 'client_stats'
Loaded module 'game_interface'
FATAL ERROR: Unable to load module 'game_buttons': /modules/corelib/ui/uiminiwindow.lua:144: attempt to call field 'getNodeSize' (a nil value)
stack traceback:
	[C]: in function 'getNodeSize'
	/modules/corelib/ui/uiminiwindow.lua:144: in function 'setup'
	/modules/game_buttons/buttons.lua:7: in function 'init'
	/modules/game_buttons/buttons.otmod:7:[@onLoad]:1: in main chunk
	[C]: in function 'ensureModuleLoaded'
	/init.lua:63: in function 'loadModules'
	/init.lua:85: in main chunk
terminate called without an active exception
Abortado (imagem do núcleo gravada)
`

**Comment by Rechdan** [comment]
@Beats-Dh having the same error now

**Comment by Beats-Dh** [comment]
Has the libzip4 error been resolved?

**Comment by Rechdan** [comment]
Yes!

**Comment by Beats-Dh** [comment]
I'm looking for a solution to this other error

**Comment by Rechdan** [comment]
Since the problem with the `libzip.so.4` is solved I'll close this issue and keep an eye on [122](https://github.com/OTCv8/otclientv8/issues/122)
