### ISSUE TITLE
Error when trying to run the client on Linux, Ubuntu 20.04 and 20.10 same error. 

### ISSUE THREAD

**Issue by Beats-Dh** [OTCv8/otclientv8#122]
​OTCv8 2.6 rev 0 (devel) made by otclient.ovh built on Nov 16 2020 for arch x64
Loaded module 'corelib'
Loaded module 'crash_reporter'
Loaded module 'gamelib'
Loaded module 'client'
Loaded module 'client_styles'
Locale 'pl' is missing 1 translations.
["Total Price:"] = "",
Locale 'pt' is missing 19 translations.
["Account Status:"] = "",
["Action:"] = "",
["Amount:"] = "",
["Balance:"] = "",
["Comment:"] = "",
["Don't stretch/shrink Game Window"] = "",
["Find:"] = "",
["Name:"] = "",
["Offer Type:"] = "",
["Piece Price:"] = "",
["Position:"] = "",
["Price:"] = "",
["Reason:"] = "",
["Search:"] = "",
["Statement:"] = "",
["Total Price:"] = "",
["Weight:"] = "",
["Your Capacity:"] = "",
["Your Money:"] = "",
Loaded module 'client_locales'
Loaded module 'client_topmenu'
Loaded module 'client_background'
Loaded module 'client_textedit'
Loaded module 'client_options'
Loaded module 'client_entergame'
Loaded module 'game_things'
Loaded module 'game_features'
Loaded module 'client_terminal'
Loaded module 'client_stats'
Loaded module 'game_interface'
FATAL ERROR: Unable to load module 'game_buttons': /modules/corelib/ui/uiminiwindow.lua:144: attempt to call field 'getNodeSize' (a nil value)
stack traceback:
        [C]: in function 'getNodeSize'
        /modules/corelib/ui/uiminiwindow.lua:144: in function 'setup'
        /modules/game_buttons/buttons.lua:7: in function 'init'
        /modules/game_buttons/buttons.otmod:7:[@onLoad]:1: in main chunk
        [C]: in function 'ensureModuleLoaded'
        /init.lua:63: in function 'loadModules'
        /init.lua:85: in main chunk
terminate called without an active exception
Abortado (imagem do núcleo gravada)

**Comment by Beats-Dh** [comment]
Possible solution to comment on line 144, then I can open the client

**Comment by OTCv8** [comment]
Hey. From 2.6 linux support has been dropped, use older version of otcv8.
