### ISSUE TITLE
Problem loading features with 8.6 version, works only if you use the character list to login.

### ISSUE THREAD

**Issue by ramon-bernardo** [OTCv8/otclientv8#126]
Client resources are not loaded on the client if the player directly login the server.
It is necessary to connect via the character list.

### feature works only if you use the character list to login.

Examples:

https://user-images.githubusercontent.com/53269692/113889100-48141c00-9799-11eb-9d1a-04d4810cd442.mp4

https://user-images.githubusercontent.com/53269692/113889109-49dddf80-9799-11eb-8307-fefe181589b4.mp4

Note:
- followed _v8/forgottenserver_ commits
- tested with _nekito downgrade-8.6_ and my downgrade _otland/master_ (last git version)

[nekito downgrade with v8 support](https://github.com/ramon-bernardo/forgottenserver/tree/8.6-downgrade)

**Comment by OTCv8** [comment]
How else would you like to do it?

**Comment by ramon-bernardo** [comment]
I tested with version 10.98 and loads when login, unlike 8.6 version that loads after using the character list to login.

This behavior is wrong, isn't it?

Note that the 'ping' resource is not loaded when logging in directly.
This happens with all resources.
