### ISSUE TITLE
RASPBERRY PI VERSION

### ISSUE THREAD

**Issue by LeoMarques101** [OTCv8/otclientv8#193]
I try to open de linux client in one raspberry pi 4 (ubunto and raspberry pi OS)(64 bits) but wasn't possible.
it will be great having a raspberry pi release

**Comment by Oen44** [comment]
Raspberry Pi is just a device, not a system. It should work with linux client.

**Comment by LeoMarques101** [comment]
> Raspberry Pi is just a device, not a system. It should work with linux client.

the linux client didn't work. i made a research and find that the problem is with the arm processor. to work it need to be compiled in a differently way

**Comment by Oen44** [comment]
Oh, true. Then there is nothing I can do, public builds are automated. I'll contact kondrah and ask him if he can add new build for ARM version.

**Comment by LeoMarques101** [comment]
> Oh, true. Then there is nothing I can do, public builds are automated. I'll contact kondrah and ask him if he can add new build for ARM version.

thanks man, it's would be amazing

**Comment by Oen44** [comment]
Talked to kondrah, not worth the time. Not many people, like probably not even dozen would use it.
