### ISSUE TITLE
'walk delay' on stairs does not work at all

### ISSUE THREAD

**Issue by gesior** [OTCv8/otclientv8#194]
`onTeleport` event is not called when player walks up/down on stairs. Tested on TFS 1.4.1 protocol 10.98.
https://github.com/OTCv8/otclientv8/blob/master/modules/game_walking/walking.lua#L23
because of that, walk delay on stairs does not work at all:
https://github.com/OTCv8/otclientv8/blob/master/modules/game_walking/walking.lua#L244-L249

I fixed it temporary by replacing:
https://github.com/OTCv8/otclientv8/blob/master/modules/game_walking/walking.lua#L230-L231
with:
```lua
function onPositionChange(player, newPos, oldPos)
  if newPos and oldPos then
    if math.abs(newPos.x - oldPos.x) >= 2 or math.abs(newPos.y - oldPos.y) >= 2 or math.abs(newPos.z - oldPos.z) >= 1 then
      onTeleport(player, newPos, oldPos)
    end
  end
end
```

**Comment by Oen44** [comment]
Shouldn't checking if newPos.z is different than oldPos.z be enough? Or using rope or walking into a hole triggers onTeleport?

**Comment by gesior** [comment]
```
Shouldn't checking if newPos.z is different than oldPos.z be enough? Or using rope or walking into a hole triggers onTeleport?
```
There are 2 delays, first for walking by stairs [floorchange], second when you teleport by 'teleport'.
I could not check, if it executes 'onTeleport', when player walks into real teleport, but it probably also does not work.
So I check, if distance is higher than 1, to execute `onTeleport` in this case.

**Comment by Oen44** [comment]
It would be hard for onTeleport to work if it's not even implemented in sources. Fixed, new update should be available in 1h.
