### ISSUE TITLE
Can't toggle anymore wings and auras with the new setoutfit menu

### ISSUE THREAD

**Issue by DoktorHolzbein** [OTCv8/otclientv8#197]
as the title says
with the new setoutfit menu Im not able to toggle/use wings, auras anymore.. Shaders itself works perfect.

I click on any random aura but it doesnt want to pull it out or something.

**Comment by Leesneaks** [comment]
This is what i posted on discord relating to this.
-----
It appears the code is incomplete, i've only scanned it quickly but aura's wings are not coded in the onElementSelect.
showWings is always false.. 
options.showwings:ischecked but i believe it should be checking showWings.check.

**Comment by Oen44** [comment]
Outfit selection module needs refactoring. Will be done soon.

**Comment by DoktorHolzbein** [comment]
it seems like its working perfectly as an gamemaster character but not has a normal player

**Comment by Oen44** [comment]
Not related to the module.
https://github.com/OTCv8/forgottenserver/blob/otclientv8/src/game.cpp#L3423=
https://github.com/OTCv8/forgottenserver/blob/otclientv8/src/game.cpp#L3434=

Change to `getWingByClientID` and `getAuraByClientID`
