### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by alkamenes** [OTCv8/otclientv8#198]
hello. Im playing on EZODUS server. I have such a problem. I can see many people dies on the similar way. The question is whather this is a problem on server side, OTC client or bot? Thanks for help.

https://www.youtube.com/watch?v=Ya8IQhwC6Yc

**Comment by Oen44** [comment]
Client is either not reading packets properly, which is caused by the server and you can't do anything about it. Or your .spr and .dat files are not the same as the server is using.

tl;dr; It has nothing to do with v8 in general.
