### ISSUE TITLE
Feature request: Actions bars

### ISSUE THREAD

**Issue by Deux88** [OTCv8/otclientv8#2]
Adding new base feature: Action bars.

Description: A dragable bar which can expand and learnt spells can be dragged to that bar.
Spells in that bar will have spellcooldown when spell is used (as number or number with color fade, etc).

Reason: All MMORPG now a days have this kind of actions bars for skills/spells which becomes way more useful with OTClient since we can use "WASD" to move, very useful.

**Comment by OTCv8** [comment]
Added
