### ISSUE TITLE
NPC Trade display bug

### ISSUE THREAD

**Issue by BahamutxD** [OTCv8/otclientv8#20]
This is happening with both TFS 1.3 and OTCv8TFS under version 10.98. 

This is not happening with OTC or Tibia Client. Using latests OTCv8

![1](https://user-images.githubusercontent.com/6182531/77167336-27a5f080-6ab6-11ea-856e-b2859cfba530.gif)

NPCs will show every item they buy/sell under both sections. Items that are not supposed to be there display wrong price value (very big number) and upon interacting with them (trying to sell) will throw an error in TFS  console. 

Under some circumstances this can freeze/crash the server. (unconfirmed)

**Comment by bbarwik** [comment]
Fixed in 2.2

**Comment by OTCv8** [comment]
Fixed in 2.2
