### ISSUE TITLE
Invalid creature / No things / etc

### ISSUE THREAD

**Issue by Diego-OT** [OTCv8/otclientv8#209]
ERROR: no creature with id 268450235
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
ERROR: invalid creature
at:
    [C++]: ?getCreature@ProtocolGame@@QAE?AV?$shared_object_ptr@VCreature@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@H@Z
ERROR: no thing
at:
    [C++]: ?parseTileTransformThing@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z
ERROR: no creature with id 268451240
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
ERROR: invalid creature
at:
    [C++]: ?getCreature@ProtocolGame@@QAE?AV?$shared_object_ptr@VCreature@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@H@Z
ERROR: no thing
at:
    [C++]: ?parseTileTransformThing@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z
ERROR: no creature with id 268451240
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z

This happens when you have more than 9 creatures in the same sqm.
I have that in my ProtocolGame::GetTileDescription but no solved:

`
const CreatureVector *creatures = tile->getCreatures();
if (creatures) {
    for (const Creature *creature : boost::adaptors::reverse(*creatures)) { 
        if (!player->canSeeCreature(creature)) {
            continue;
        }
        if(otclientV8 && count == 10) break;

        bool known;
        uint32_t removedKnown;
        checkCreatureAsKnown(creature->getID(), known, removedKnown);
        AddCreature(msg, creature, known, removedKnown);
        ++count;
    }
}
`

**Comment by Oen44** [comment]
Enable `GameNewCreatureStacking`

**Comment by Oen44** [comment]
Also make sure you have this https://github.com/otland/forgottenserver/pull/2673
