### ISSUE TITLE
Action Bar bug when assigning hotkey

### ISSUE THREAD

**Issue by BahamutxD** [OTCv8/otclientv8#21]
Using latest OTCv8 - when adding hotkey to an action it will bug the action bar module and will stop working throwing this error.

`ERROR: protected lua call failed: /modules/game_actionbar/actionbar.lua:147: attempt to index field 'hotkey' (a number value)
stack traceback:
    [C]: in function '__index'
    /modules/game_actionbar/actionbar.lua:147: in function 'setupAction'
    /modules/game_actionbar/actionbar.lua:112: in function 'setupActionPanel'
    /modules/game_actionbar/actionbar.lua:69: in function 'show'
    /modules/game_actionbar/actionbar.lua:91: in function </modules/game_actionbar/actionbar.lua:90>`

This bug  was introduced with 2.1 changes - older versions works fine.

**Comment by OTCv8** [comment]
Fixed in 2.2
