### ISSUE TITLE
Problem when trying to enter OT CANARY 13.1... Through the mobile client.

### ISSUE THREAD

**Issue by Nilvagner** [OTCv8/otclientv8#233]
I configured to access the server in offline mode, wifi local network. I manage to get to the screen to choose the character, when I choose and enter, it shows the following error in the canary console:

[ProtocolGame: :onRecvFirstMessage] RSA Decrypt Failed

I found this line in the mobile client files, in the ENTERGAME.LUA file:

   -- if you have custom rsa or protocol edit it here
   g_game.setClientVersion(G.clientVersion)
   g_game.setProtocolVersion(g_game.getClientProtocolVersion(G.clientVersion))
   g_game.setCustomProtocolVersion(0)
   g_game.setCustomOs(-1) -- disable
   g_game.chooseRsa(G.host)
   if #server_params <= 3 and not g_game.getFeature(GameExtendedOpcode) then
     g_game.setCustomOs(2) -- set os to windows if opcodes are disabled
   end

**Comment by Oen44** [comment]
13.X not supported.

**Comment by Oen44** [comment]
No, full support ends at 10.98, after that its just unfinished work.

**Comment by Nilvagner** [comment]
thy!
