### ISSUE TITLE
Transparency broken

### ISSUE THREAD

**Issue by BahamutxD** [OTCv8/otclientv8#24]
Since 2.2 transparency seems to not display floors below.

The transparency itself works but displays black below it.

2.2 vs 2.1 shots

![image](https://user-images.githubusercontent.com/6182531/78082914-6e4bf280-73b4-11ea-9a8b-100be043b8b9.png)

![image](https://user-images.githubusercontent.com/6182531/78082946-828fef80-73b4-11ea-9a60-c9f5fcd1f7ae.png)

If someone can confirm the issue please.

**Comment by Caduceus** [comment]
![Transparency1](https://user-images.githubusercontent.com/5316739/81970466-72367b80-95d4-11ea-9633-ae4f4af66d0c.PNG)

Having same issue.

**Comment by OTCv8** [comment]
Corrected in 2.4
