### ISSUE TITLE
Floor fading

### ISSUE THREAD

**Issue by BahamutxD** [OTCv8/otclientv8#26]
Floor fading feature been broken for some updates now.

Even with Enable Lights - disabled it won't work. No errors in console.

**Comment by OTCv8** [comment]
Not enough info, tell how to reproduce this bug

**Comment by BahamutxD** [comment]
> Not enough info, tell how to reproduce this bug

Upon further testing - enabling transparency stops this feature from working.

**Comment by OTCv8** [comment]
Fixed in 2.4
