### ISSUE TITLE
Walking down from pyramids on 7.6

### ISSUE THREAD

**Issue by DrzazgaSebastian** [OTCv8/otclientv8#31]
There is an issue with walking down from some pyramids on 7.6. When I was looking at the edges, those pyramids that are problematic had ID 1316 or 1961, those that were working properly had ID 469.

**Comment by DrzazgaSebastian** [comment]
Checked this one with new version and the problem is not fixed unfortunately. If I can provide more info about that or you need anything to know to fix the problem, tell me and I'm gonna do my best to help.

**Comment by OTCv8** [comment]
Fixed in 2.3.1

**Comment by DrzazgaSebastian** [comment]
There is new problem with walking. Now, when moving by mouse, character is trying to step on invisible creatures instead of walking around. :/
