### ISSUE TITLE
actions problem

### ISSUE THREAD

**Issue by unlineworld** [OTCv8/otclientv8#32]
it is not possible to do some quests because the actions do not work for this client, for example click on something to do a mission
![image](https://user-images.githubusercontent.com/51373120/79357725-c9cec200-7f16-11ea-838f-877d64eaf220.png)

like this quest The Ape city quest, it is not possible to do it using otclient only with other clients like 10 or version 12

**Comment by OTCv8** [comment]
it was fixed in 2.3, what version do you have?
