### ISSUE TITLE
4 days of VIP disappeared.

### ISSUE THREAD

**Issue by Sayani2001** [OTCv8/otclientv8#36]
Yesterday I created my account (April 19) and a message appeared that I had almost 5 days of VIP, today when I connect it appears to me that I have 12 hours of VIP only.
![2](https://user-images.githubusercontent.com/58892594/79812497-bff5f600-833e-11ea-9929-54b232ac8b3e.png)
![1](https://user-images.githubusercontent.com/58892594/79812499-c08e8c80-833e-11ea-85ba-214e56556a95.png)

Nick: Sayani Azaroni
Discord: Sayani#0001

**Comment by kygov** [comment]
Is it bug related to otcv8?
