### ISSUE TITLE
Key and Outfits

### ISSUE THREAD

**Issue by sm0Lax** [OTCv8/otclientv8#44]
My outfits are broken. https://imgur.com/a/mAM2Pe1  
Also key (id:2969) have not worked (i cant use it on the doors), when others keys work fine. 
I check the both problem on another OTC Client and there all was good.
What's wrong, where i have to look for problem?

I play on 7.6

**Comment by OTCv8** [comment]
Should be corrected in 2.5, if not please reopen issue
