### ISSUE TITLE
Light spells disappearing

### ISSUE THREAD

**Issue by Caduceus** [OTCv8/otclientv8#51]
I am having issues with light spells disappearing when player steps on larger creature corpses, ie dragon, demon, Hydra. When player steps off of corpse, light spell reappears. Issue is happening in both dx and gl versions. 

![Screenshot_20200524-093553_Discord](https://user-images.githubusercontent.com/5316739/82759524-ddd1d300-9da2-11ea-9f07-4627eef25881.jpg)

**Comment by BahamutxD** [comment]
Can confirm

https://gfycat.com/vacantcrazylarva

**Comment by OTCv8** [comment]
Thanks. Fixed
