### ISSUE TITLE
Light seem to disapear after killing monsters

### ISSUE THREAD

**Issue by 4mrcn4** [OTCv8/otclientv8#52]
Issue is occuring on 2.4 preview and couldn't be reproduced using 2.3.1

If the issue is not known ill investigate further

![lightbug](https://user-images.githubusercontent.com/51740363/82946266-52bd2c80-9f9e-11ea-9bd1-852393402ce7.gif)

**Comment by Caduceus** [comment]
Refer to issue #51

**Comment by 4mrcn4** [comment]
dang, must have missed it :(
closing
