### ISSUE TITLE
Can't login after encrypting

### ISSUE THREAD

**Issue by eCov19** [OTCv8/otclientv8#53]
I got this error when trying to connect, I followed this guide:
(https://www.youtube.com/watch?v=RzEZ__Iq9-s)

![image](https://user-images.githubusercontent.com/62757552/83374263-16703e80-a399-11ea-919f-3a1c883647c7.png)
PS: I didn't find login.php file :/

**Comment by OTCv8** [comment]
Just add missing files before encrypting
