### ISSUE TITLE
cavebot_1.2 Bug Android Client

### ISSUE THREAD

**Issue by dstmaloka** [OTCv8/otclientv8#54]
Turn ON/OFF cavebot clean waypoints

![Screenshot_2020-06-01-11-22-28](https://user-images.githubusercontent.com/49885720/83418912-b0b49e80-a3fa-11ea-8bbf-d758e6c54089.png)

![Screenshot_2020-06-01-11-22-35](https://user-images.githubusercontent.com/49885720/83418905-af837180-a3fa-11ea-9bdb-973b3368c37a.png)

**Comment by OTCv8** [comment]
Fixed
