### ISSUE TITLE
Height objects will push up doors and other items on the tile

### ISSUE THREAD

**Issue by 4mrcn4** [OTCv8/otclientv8#55]
![zjebanie](https://user-images.githubusercontent.com/51740363/84287092-c3884b00-ab3f-11ea-87d8-5c33fefdf70f.gif)

It affects all objects on tile that are being displayed on the top - things like doors or hanging ceilings and so on.

Occurs on 2.4, Couldnt been reproduced using 2.31

**Comment by OTCv8** [comment]
Fixed in next commit
