### ISSUE TITLE
Moving around some windows causes laggs on version 2.4+

### ISSUE THREAD

**Issue by strndi** [OTCv8/otclientv8#57]
If you move the skills window around, the client will lagg, if you keep moving it you will hit 0 FPS. In previous versions there was no laggs moving windows around.
The console is also spammed with these messages while moving such a window around:
ERROR: ATTENTION the event list is not getting empty, this could be caused by some bad code.
Log:
WIN32Window::poll
WIN32Window::poll
WIN32Window::poll
UILayout::updateLater

I found that the skill and spell list window causes these issues, but there might be more windows which are affected,

**Comment by imranhhk** [comment]
I'm experiencing a similar issue after the 2.4+ update. 
Whenever any window opens like: Skill, Modal Windows etc the client begins to freeze very badly.
If I revert the changes back to 2.3.1 then it's working fine again.

**Comment by OTCv8** [comment]
Corrected in 2.5
