### ISSUE TITLE
Custom user agent for websockets

### ISSUE THREAD

**Issue by Znote** [OTCv8/otclientv8#59]
My guess is that somewhere here: https://github.com/OTCv8/otclientv8/blob/master/src/framework/http/http.cpp

You should be able to change the user agent the client uses when sending get/post requests to the server. 

I would like to change the user agent to `Mozilla/5.0` as thats what client 11/12 uses, and thus also me when identifying wether a [request to login.php](https://github.com/Znote/ZnoteAAC/blob/203fe3d5ae08eeaf58cbf0956bb2a847e200f16b/login.php#L7) should be handled on the website (Znote AAC) or the client (json communication). 

Do you think you could add this, or tell me how to add it to this client?

**Comment by OTCv8** [comment]
Yes, in 2.4.2, will be configurable in modules/corelib/http.lua

**Comment by OTCv8** [comment]
Added in 2.4.2, including tibia 12 http login support, works fine with znode
