### ISSUE TITLE
Swedish character display issue

### ISSUE THREAD

**Issue by Appzyt** [OTCv8/otclientv8#6]
When using swedish characters (åäö) at the server end it often prevents the entire word to be displayed. Like such: https://share.getcloudapp.com/4gu7lBJO (see the far right side of the wall of text)

The problem is present in all forms of text, sendTextMessage, questlog, npc etc and has been this way since public release of the client and was not a problem in the original OTClient. The .lua and .xml files are coded in ANSI.

**Comment by OTCv8** [comment]
Fixed
