### ISSUE TITLE
Interface problem on some Android devices - Target and Cavebot

### ISSUE THREAD

**Issue by drvaderr** [OTCv8/otclientv8#60]
![Screenshot_20200622-031022](https://user-images.githubusercontent.com/67288039/85322908-b39c2f80-b48c-11ea-8589-7b39ba85c2f4.jpeg)
The target window is too big to be edited.

![Screenshot_20200622-133552](https://user-images.githubusercontent.com/67288039/85323314-62d90680-b48d-11ea-92a1-b7a1cd633bcc.jpeg)
This is the data from my android device.

Is there any requirement for android? help me please

**Comment by OTCv8** [comment]
It will be redesigned to fit mobile version within few days

**Comment by drvaderr** [comment]
Thank you! I love your work very much, at some point I will donate you :")
