### ISSUE TITLE
The downloadable versions are corrupted.

### ISSUE THREAD

**Issue by loquesiendo** [OTCv8/otclientv8#61]
The downloadable versions are corrupted.

Sometimes I cannot download some updates and it tells me that I have to install this version manually.

Is this due to an error?

It also happens on my Huawei T3 8 (Android 5.0 Lollipop)

I can download versions like for example: 10.99
 8.60 
But in some cases I can't download versions like: 
7.4 
7.6.

![image png 1656b2a2170a8d98082a3fcbee24da93](https://user-images.githubusercontent.com/67662133/86180272-64d84080-baf1-11ea-821b-a6704c1e624b.png)

**Comment by OTCv8** [comment]
Apk file can't be updated automatically on android, so you need to reinstall it. That's normal
