### ISSUE TITLE
Bug on Logig

### ISSUE THREAD

**Issue by KonigDerLowen** [OTCv8/otclientv8#63]
![image](https://user-images.githubusercontent.com/67932691/86667916-7f665a00-bfc8-11ea-99d3-bf4518d8ba45.png)

I'm having this problem on 2 servers. I'm using the server right version. One server i logged in, played for a day, and it was all good, i went up stairs and it got bugged like this. 

I tried to relog, restarted my pc, logged on another folder i have to make sure it didnt get corrupted. Nothing worked

**Comment by OTCv8** [comment]
Include log from terminal and packet.log file if exist, use latest version
