### ISSUE TITLE
Effects pattern calculation fix

### ISSUE THREAD

**Issue by Oen44** [OTCv8/otclientv8#64]
Effects with patterns are disappearing when you move.
https://streamable.com/h8zbkf

https://github.com/OTCv8/otclientv8/blob/master/src/client/effect.cpp#L49-L55

Change these lines to
```cpp
int xPattern = m_position.x % getNumPatternX();
int yPattern = m_position.y % getNumPatternY();
```

**Comment by OTCv8** [comment]
Changed in 2.5.1, thanks
