### ISSUE TITLE
Too much light around own player character

### ISSUE THREAD

**Issue by 4mrcn4** [OTCv8/otclientv8#65]
Even with the lowest ambient light setting, which is 0, there is too much light around the player's character.

Repro steps:
1. Log onto the non-access character
2. Enter dark place, eg. thais rats.
3. Tick "enable lights", set ambient light to 0.

Expected behavior:
There is little to none light around the character.

Current behavior:
There is light being rendered on the client-side.

On gif, you can see that it's not server-side, the characters are not sending any light.
![toomuchlight](https://user-images.githubusercontent.com/51740363/86976597-1f63e500-c17b-11ea-9e0a-aa5c0ca39cb4.gif)

Issue occurs on TFS1.3, OTCv8 2.4.1, and previous versions.

**Comment by OTCv8** [comment]
Lowered in 2.5.1
