### ISSUE TITLE
Minor Outfit/Mount animation issues

### ISSUE THREAD

**Issue by imranhhk** [OTCv8/otclientv8#7]
1. There are a few mounts the newer clients which have idle animation phases which are a little buggy: Fleeting Knowledge, Jousting Eagle and Cereberus Champion
https://gyazo.com/3508dff0210cfbe95406d500d4bc46c9

2. Outfits which have the "animate always" tag are a little buggy when walking:
https://gyazo.com/8db8333d0f3c52c6c21948b53b2c690d

Sorry for the poor quality on the gifs

**Comment by bbarwik** [comment]
fixed in 1.3

**Comment by OTCv8** [comment]
Fixed in 1.3

**Comment by imranhhk** [comment]
@OTCv8 Awesome! <3 #1 was fixed but the issue #2 with "Always Animate" is still bugged when walking.
