### ISSUE TITLE
email login - tibia 12+

### ISSUE THREAD

**Issue by Methemia** [OTCv8/otclientv8#70]
How can I connect by email?
I am using this server
https://github.com/opentibiabr/otservbr-global
on this server, they changed the account by email (as in tibia RL - cipsoft)

**Comment by Tazer89** [comment]
> How can I connect by email?
> I am using this server
> https://github.com/opentibiabr/otservbr-global
> on this server, they changed the account by email (as in tibia RL - cipsoft)

Its coming soon. Wait for next update.

**Comment by OTCv8** [comment]
Just enter email instead account name
