### ISSUE TITLE
Getting screen glitch when going into a big stack

### ISSUE THREAD

**Issue by nortram** [OTCv8/otclientv8#77]
Hello,
me and other guild mates are having an annoying issue when we get into a stack where there are a lot of people (war, quests, ect)
the screen freezes and you can't do nothing, you can see map and hp /mp moving, but only thing you can do is restart the client,
it's currently happening with 2.5.3, but it's happening to me since 2.4.0
same happens using openGL and DX

settings:
cpu: i5-4670 
24gb ram ddr3
graphic card: nvidia gtx 1660 super with latests drivers
windows 10 pro 64 bits 19041
dx12

doesnt matter what I set into options-graphics,

thanks in advance.

**Comment by OTCv8** [comment]
it's server side issue
