### ISSUE TITLE
otclient - 12.40 bug

### ISSUE THREAD

**Issue by Briluxxx** [OTCv8/otclientv8#79]
https://imgur.com/iNLZslf

happens only in version 12.40 of OTserv-BR, in version 12.20 it works fine

I am using the most recent version and of the page I use ZnoteACC

**Comment by Briluxxx** [comment]
https://imgur.com/wH57D1l




at:
    [C++]: ?parseCreatureMove@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z
ERROR: no thing at pos:32370 32242 7, stackpos:1
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
ERROR: invalid creature
at:
    [C++]: ?getCreature@ProtocolGame@@QAE?AV?$shared_object_ptr@VCreature@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@H@Z
ERROR: no thing
at:
    [C++]: ?parseTileTransformThing@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z
ERROR: no thing at pos:32370 32242 7, stackpos:1
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
ERROR: invalid creature
at:
    [C++]: ?getCreature@ProtocolGame@@QAE?AV?$shared_object_ptr@VCreature@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@H@Z
ERROR: no thing
at:
    [C++]: ?parseTileTransformThing@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z
ERROR: no thing at pos:32368 32242 7, stackpos:1
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
ERROR: invalid creature
at:
    [C++]: ?getCreature@ProtocolGame@@QAE?AV?$shared_object_ptr@VCreature@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@H@Z
ERROR: no thing
at:
    [C++]: ?parseTileTransformThing@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z
ERROR: no thing at pos:32368 32242 7, stackpos:1
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
ERROR: invalid creature
at:
    [C++]: ?getCreature@ProtocolGame@@QAE?AV?$shared_object_ptr@VCreature@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@H@Z
ERROR: no thing
at:
    [C++]: ?parseTileTransformThing@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z
ERROR: no thing at pos:32370 32239 7, stackpos:1
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
ERROR: no creature found to move
at:
    [C++]: ?parseCreatureMove@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z
WARNING: message in channel id 3 which is unknown, this is a server bug, relogin if you want to see messages in this channel
ERROR: no thing at pos:32370 32238 7, stackpos:1
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
ERROR: no creature found to move
at:
    [C++]: ?parseCreatureMove@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z

**Comment by OTCv8** [comment]
12.40 is not supported, partial support from 2.6
