### ISSUE TITLE
Item and Invisible animation ticks

### ISSUE THREAD

**Issue by imranhhk** [OTCv8/otclientv8#8]
Hey Kondrah,

Is it possible to edit these values to 100 each:

INVISIBLE_TICKS_PER_FRAME = 500
ITEM_TICKS_PER_FRAME = 500

Currently these animations appear very slow:
1) Player imitating item
https://gyazo.com/7ed5dc95cd57ce7e1206f5293854104c

2) Player is invisible
https://gyazo.com/e898fed67127624aacbebecd0ce70c4d

The location they are used:
https://github.com/edubart/otclient/blob/e3b02a7c5dd7ad58474b2874305a9f4c4dfcadd0/src/client/creature.cpp#L165

**Comment by OTCv8** [comment]
yes, changed in 1.2
