### ISSUE TITLE
Red frame around the player's "invisible" taget is misaligned

### ISSUE THREAD

**Issue by 4mrcn4** [OTCv8/otclientv8#84]
![image](https://user-images.githubusercontent.com/51740363/93533009-65d77c00-f942-11ea-879d-253c484129e6.png)

Repro steps:
1. Log in two characters
2. Put stealth ring on first 
3. Target the first character with second character

CB: Red frame around the target is misaligned.
EB: Red frame is aligned around the target.

The issue occurs with other types of frames, like the one that appears around the player character (if invisible) while being attacked.

The issue has been observed using TFS 1.3 and OTCv8 2.5.7

**Comment by 4mrcn4** [comment]
Small update - the issue occurs with other types of frames, like the one that appears around the player character while being attacked.

**Comment by OTCv8** [comment]
Corrected
