### ISSUE TITLE
You are not allowed to shoot directly on player (Tibia version 7.72)

### ISSUE THREAD

**Issue by MasterChenSensei** [OTCv8/otclientv8#9]
Hey, I have this problem, as far as I know it's only in version 7.72, and it seems to be on some servers only, where I cannot use hotkey to heal myself with runes or even fluids, also cannot attack players with runes, nor is it possible doing so manually. It gives me the message "You are not allowed to shoot directly on player", however, it works fine using on other creatures, just not on myself.

I've tried on the same servers and the same versions with the regular OTClient, and there it works just fine.

**Comment by OTCv8** [comment]
Should be fixed from 1.9
