### ISSUE TITLE
Updater: HTTP library missing files (?)

### ISSUE THREAD

**Issue by okk3** [OTCv8/otclientv8#92]
Hello there,

I've been trying to port the updater of this distribution to edubarts otclient, I noticed that the http.cpp file has an include to stats.h, which isn't needed to download the files and isn't available in the free distribution, which is just fine. but then it also has an include to session.h, which I think is part of the code for `Http::get`, as seen on the image below:

![image](https://user-images.githubusercontent.com/34428344/99913960-cdbb9180-2cfa-11eb-9c12-cf250271a81a.png)

![image](https://user-images.githubusercontent.com/34428344/99910837-92b46080-2cf0-11eb-8dfb-48cf468a2fef.png)

The dispacher addEventEx function can be easily copied over, so I'd be missing the session.h file, is there a reason why this file hasn't been published? Is it only for the paid version of this distribtion?

Thanks in advance and best wishes
Okke

**Comment by OTCv8** [comment]
It's not open sourced, can sell you that for $500.

**Comment by okk3** [comment]
Sad you still try to make money from people in an "open-source" using something I helped create, for free.

I would never pay 500$ for something that's just lying around, you must be nuts and a mercenary.
