### ISSUE TITLE
Player has to compensate for creature movement while targeting with RMB.

### ISSUE THREAD

**Issue by 4mrcn4** [OTCv8/otclientv8#96]
![rightclickissue](https://user-images.githubusercontent.com/51740363/101780791-42623e80-3af7-11eb-9751-60b6a5707c55.gif)

2.6 introduced an issue that could've been reproduced on 2.57.
When a user tries to target a moving creature, it mapclicks instead - to explain it in tibianish way, right-click targeting works like a 7.4 rune would, you have to predict creature movement to attack it, which is not expected behavior.

Steps to reproduce:
1. Summon a minotaur archer and start moving.
3. Try to target the monster using rightclick, right after its steps.

Current behavior: Player has to compensate for creature movement or he will autowalk.
Expected behavior: The player is able to target the creature targeting their outfit.
Env: 2.6

**Comment by OTCv8** [comment]
Corrected in 2.6.1
